izanagi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('susanowo/', include('susanowo.urls')),
    path('guestboard/', include('guestboard.urls')), 
    # url(r'^guestboard/', include(('guestboard.urls', 'guestboard'),)), 
    # path('uploader/', include('uploader.urls')), 
    url(r'^uploader/', include('uploader.urls')), 
    path('omoikane/', include('omoikane.urls')),
    path('tukuyomi/', include('tukuyomi.urls')),
    path('amaterasu/', include('amaterasu.urls')),
    path('amenouzume/', include('amenouzume.urls')),
    path('sarutahiko/', include('sarutahiko.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

omoikane/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "omoikane"
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^main/$', views.main, name='main'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^login_input/$', views.login_input, name='login_input'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    path('user_input_modify/<str:user_id>/<str:shori>/', views.user_input_modify, name='user_input_modify'),
    url(r'^user_input/$', views.user_input, name='user_input'),
    url(r'^menu_list/$', views.menu_list, name='menu_list'),
    path('menu_input_modify/<int:id>/<str:shori>/', views.menu_input_modify, name='menu_input_modify'),
    url(r'^menu_input/$', views.menu_input, name='menu_input'),
    url(r'^auth_header/$', views.auth_header, name='auth_header'),
    url(r'^auth_list/$', views.auth_list, name='auth_list'),

]

omoikane/models.py
from django.db import models
from django.utils.timezone import now
from django.shortcuts import render

# Create your models here.
class MUser(models.Model):
    user_id = models.CharField(
        verbose_name='ユーザID',
        max_length=30,
        help_text='システムにログインするIDを入力してください',
        blank=False,
    )
    user_name = models.CharField(
        verbose_name='ユーザ名',
        max_length=30,
        help_text='お名前を入力してください',
        default=''
    )
    password = models.CharField(
        verbose_name='パスワード',
        max_length=30,
        help_text='システムにログインするパスワードを入力してください',
        blank=False,
    )
    admin_auth = models.BooleanField(
        verbose_name='管理者権限',
        blank=False,
        default=False,
    )
    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )
    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )
    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )
    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

def get_upload_dir(instance, filename):
    return 'omoikane/icon/{0}/{1}'.format(instance.id,instance.icon)

class MMenu(models.Model):
    id = models.AutoField(
        primary_key=True,
        verbose_name='メニューID',
    )
    menu_name = models.CharField(
        verbose_name='メニュー名称',
        max_length=50,
        help_text='システム名を入力してください',
        blank=False,
        default=''
    )
    url = models.CharField(
        verbose_name='URL',
        max_length=100,
        help_text='システムのURLを入力してください',
        blank=False,
        default=''
    )
    icon = models.ImageField(
        verbose_name='リンクアイコン',
        upload_to=get_upload_dir,
        blank=True,
        null=True,
    )
    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )
    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )
    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )
    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

class MAuth(models.Model):
    user_id = models.CharField(
        verbose_name='ユーザID',
        max_length=30,
        help_text='システムにログインするIDを入力してください',
        blank=False,
    )

    menu_id = models.CharField(
        verbose_name='メニューID',
        max_length=30,
        blank=True,
    )

omoikane/views.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
from omoikane import const
from omoikane import forms
from omoikane.forms import (
    LoginModelForm, 
    UserInputModelForm, 
    UserModifyModelForm, 
    UserDeleteModelForm,
    MenuInputModelForm,
    MenuModifyModelForm,
    MenuDeleteModelForm,
    AuthHeaderForm,
    AuthListForm,
    AuthListFormSet,
)
from omoikane.models import (
    MUser,
    MMenu,
    MAuth,
)
import datetime
import logging
import os
from izanagi import settings
from django.forms import formsets


# Create your views here.
# ログイン画面
def login(request):
    if request.method == 'GET':
        form = LoginModelForm(request.GET or None)
        context = {
            'form': form
        }
        return render(request, 'omoikane/login.html',context)
    elif request.method == 'POST':
        form = LoginModelForm(request.POST)
        if not form.is_valid():
            context = {
                'form': form
            }
            return render(request, 'omoikane/login.html', context)
        
        user_id = form.cleaned_data['user_id']
        user = MUser.objects.get(user_id=user_id)
        request.session['LOGIN_USER_ID'] = user.user_id
        request.session['LOGIN_USER_NAME'] = user.user_name
    return redirect('/omoikane/menu/')
    # return render(request, 'omoikane/menu.html')

def menu(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

        auth_list = MAuth.objects.filter(user_id=user_id).order_by('menu_id')
        menu_list = []
        for auth in auth_list:
            menu = MMenu.objects.get(id=auth.menu_id)
            data = {
                'menu_name':menu.menu_name,
                'url':menu.url,
                'icon':menu.icon,
            }
            menu_list.append(data)
        
        context = {
            'menu_list': menu_list,
            'user_id': user_id,
            'user_name': user_name,
        }
        return render(request, 'omoikane/menu.html',context)

def main(request):
    context = {
        'user_id':request.session.get('LOGIN_USER_ID'),
        'user_name':request.session.get('LOGIN_USER_NAME'),
    }
    return render(request, 'omoikane/main.html',context)

def login_input(request):
    if request.method == 'GET':
        form = UserInputModelForm(request.GET or None)
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'form': form,
            'shori': '',
            'title': const.USER_SHORI['']
        }
        return render(request, 'omoikane/login_input.html',context)
    elif request.method == 'POST':
        form = UserInputModelForm(request.POST)
        if not form.is_valid():
            context = {
                'user_id':request.session.get('LOGIN_USER_ID'),
                'user_name':request.session.get('LOGIN_USER_NAME'),
                'form': form,
                'title': const.USER_SHORI['']
            }
            return render(request, 'omoikane/login_input.html', context)
        form.save()
        return redirect('/omoikane/')

def user_list(request):
    if request.method == 'GET':
        musers = MUser.objects.all().order_by('user_name')
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'musers': musers
        }
        return render(request, 'omoikane/user_list.html',context)

def user_input_modify(request,user_id,shori):
    if request.method == 'GET':
        muser = MUser.objects.get(user_id=user_id)
        form = UserModifyModelForm(instance=muser)
        context = {
            'form': form,
            'user_id': user_id,
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'shori': shori,
            'title': const.USER_SHORI[shori],
        }
        return render(request, 'omoikane/user_input.html',context)
    elif request.method == 'POST':
        muser = get_object_or_404(MUser, user_id=user_id)
        if shori=='m':
            form = UserModifyModelForm(request.POST)
            if not form.is_valid():
                context = {
                    'form': form,
                    'user_id': user_id,
                    'user_name':request.session.get('LOGIN_USER_NAME'),
                    'shori': shori,
                    'title': const.USER_SHORI[shori],
                }
                return render(request, 'omoikane/user_input.html',context)
            
            muser.user_name = form.cleaned_data['user_name']
            if not form.cleaned_data['password1']=='':
                muser.password = form.cleaned_data['password1']
            muser.update_date = timezone.datetime.now()
            muser.update_pg_id = 'omoikane.user_input'
            muser.updaet_user_id = 'admin'
            muser.save()
            return redirect('/omoikane/user_list/')

        elif shori=='d':
            form = UserDeleteModelForm(request.POST)
            if not form.is_valid():
                context = {
                    'form': form,
                    'user_id': user_id,
                    'user_name':request.session.get('LOGIN_USER_NAME'),
                    'shori': shori,
                    'title': const.USER_SHORI[shori],
                }
                return render(request, 'omoikane/user_input.html',context)
            
            muser.delete()
            return redirect('/omoikane/user_list/')

def user_input(request):
    if request.method == 'GET':
        form = UserInputModelForm(request.GET or None)
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'form': form,
            'shori': '',
            'title': const.USER_SHORI[''],
        }
        return render(request, 'omoikane/user_input.html',context)
    elif request.method == 'POST':
        form = UserInputModelForm(request.POST)
        if not form.is_valid():
            context = {
                'user_id':request.session.get('LOGIN_USER_ID'),
                'user_name':request.session.get('LOGIN_USER_NAME'),
                'form': form,
                'shori': '',
                'title': const.USER_SHORI[''],
            }
            return render(request, 'omoikane/user_input.html', context)
        form.save()
        return redirect('/omoikane/user_list/')

def menu_list(request):
    if request.method == 'GET':
        mmenus = MMenu.objects.all().order_by('id')
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'mmenus': mmenus
        }
        return render(request, 'omoikane/menu_list.html',context)

def menu_input(request):
    if request.method == 'GET':
        form = MenuInputModelForm(request.GET or None)
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'form': form,
            'shori': '',
            'title': const.MENU_SHORI[''],
        }
        return render(request, 'omoikane/menu_input.html',context)
    elif request.method == 'POST':
        form = MenuInputModelForm(request.POST)
        if not form.is_valid():
            context = {
                'user_id':request.session.get('LOGIN_USER_ID'),
                'user_name':request.session.get('LOGIN_USER_NAME'),
                'form': form,
                'shori': '',
                'title': const.MENU_SHORI[''],
            }
            return render(request, 'omoikane/menu_input.html', context)
        mmenu = MMenu()
        mmenu.menu_name = request.POST['menu_name']
        mmenu.url = request.POST['url']
        if request.POST['icon']:
            mmenu.icon = request.FILES['icon']
        mmenu.create_date = timezone.datetime.now()
        mmenu.create_pg_id = 'omoikane.update_input'
        mmenu.create_user_id = 'admin'
        mmenu.update_date = timezone.datetime.now()
        mmenu.update_pg_id = 'omoikane.update_input'
        mmenu.updaet_user_id = 'admin'
        mmenu.save()
        return redirect('/omoikane/menu_list/')

def menu_input_modify(request,id,shori):
    if request.method == 'GET':
        mmenu = MMenu.objects.get(pk=id)
        initialize = {
            'menu_id':id,
            'menu_name':mmenu.menu_name,
            'url':mmenu.url,
            'icon':mmenu.icon,
        }
        form = MenuModifyModelForm(initial=initialize)
        context = {
            'user_id':request.session.get('LOGIN_USER_ID'),
            'user_name':request.session.get('LOGIN_USER_NAME'),
            'form': form,
            'id': id,
            'shori': shori,
            'title': const.MENU_SHORI[shori],
        }
        return render(request, 'omoikane/menu_input.html',context)
    elif request.method == 'POST':
        mmenu = get_object_or_404(MMenu, pk=id)
        # imagePath = mmenu.icon
        if shori=='m':
            form = MenuModifyModelForm(request.POST, files=request.FILES or None)
            if not form.is_valid():
                context = {
                    'user_id':request.session.get('LOGIN_USER_ID'),
                    'user_name':request.session.get('LOGIN_USER_NAME'),
                    'form': form,
                    'id': id,
                    'shori': shori,
                    'title': const.MENU_SHORI[shori],
                }
                return render(request, 'omoikane/menu_input.html',context)

            # mmenu.id = form.cleaned_data['menu_id']
            # mmenu.menu_name = form.cleaned_data['menu_name']

tukuyomi/views/loginView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
import logging
import os
from izanagi import settings
from tukuyomi.forms.loginForm import LoginModelForm
from omoikane.models import MUser

def login(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        form = LoginModelForm(request.GET or None)
        context = {
            'form': form
        }

        if user_id:
            return redirect('/tukuyomi/menu/')

        return render(request, 'tukuyomi/login.html',context)

    elif request.method == 'POST':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        if user_id is None:
            user_id = request.POST['user_id']
            user = MUser.objects.get(user_id=user_id)
            user_name = user.user_name
            request.session['LOGIN_USER_ID'] = user.user_id
            request.session['LOGIN_USER_NAME'] = user.user_name

        form = LoginModelForm(request.POST)
        if form.is_valid():
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id': user_id,
                'user_name': user_name,
                'form': form,
            }
            return render(request, 'tukuyomi/login.html', context)

tukuyomi/views/menuView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
    reverse,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
from datetime import datetime
import logging
import os
from tukuyomi import tukuyomiConst
from tukuyomi.models.mbuyer import MBuyer

def menu(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

    # 定数初期化
    mbuyers = MBuyer.objects.filter(user_id=user_id).order_by('buyerNm')
    tukuyomiConst.BUYER_CHOICE = []
    tukuyomiConst.BUYER_CHOICE.append((None, ''))
    for buyer in mbuyers:
        tukuyomiConst.BUYER_CHOICE.append((buyer.id, buyer.buyerNm))

    context = {
        'user_id':user_id,
        'user_name':user_name,
        'now_year':datetime.strftime(datetime.now(), '%Y'),
        'now_month':datetime.strftime(datetime.now(), '%m'),
        # 'now_year':datetime.strftime(datetime.today(), '%Y'),
        # 'now_month':datetime.strftime(datetime.today(), '%m'),
        'form': None,
    }

    return render(request, 'tukuyomi/menu.html',context)

templates/omoikane/auth_list.html
{% extends "omoikane/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/omoikane/auth_list.js' %}" ></script>
{% endblock %}

{% block body %}
権限付与<br/>
    
<form method="post" action="{% url 'omoikane:auth_header' %}">
    {% csrf_token %}
    {{user.user_name}}
    <input type="submit" value="検索" id="btnUserList" class="square_btn" />
</form>

<form method="post" action="{% url 'omoikane:auth_list' %}">
    {% csrf_token %}
    <input type="hidden" id="id_user_id" name="user_id" value="{{cmb_user_id}}" />
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:350px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_class" style='width:50px'>選択</th>
                        <th class="th_class" style='width:300px'>メニュー名</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:350px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#BBBBBB">
            {{ form.management_form }}
            <table class="list_class">
                <tbody name="auth">
                {% for menu in form %}
                    <tr id="row">
                        <td class="td_class" style='width:50px'>
                            {{menu.is_select}}
                        <td>
                        <td class="td_class" style='width:300px'>
                            {{menu.menu_name}}
                        </td>
                        <td>
                            {{menu.menu_id}}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>
    <table id="controller">
        <tr>
            <td style="text-align:center;"><input type="submit" value="登録" class="square_btn" /></td>
            <td style="text-align:center;"><input type="button" id="btn_cancel" value="キャンセル" class="square_btn" /></td>
        </tr>    
    </table>

{% endblock %}

templates/omoikane/main.html
{% extends "omoikane/base.html" %}

{% load static %}
{% block header %}
{% endblock %}

{% block body %}
システムを利用するユーザIDの管理、<br/>
メニューの追加とユーザごとの利用管理<br/>
を設定するシステムです。<br/>
{% endblock %}

templates/omoikane/menu_input.html
{% extends "omoikane/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/omoikane/menu_input.js' %}" ></script>
{% endblock %}

{% block body %}
{{title}}<br/>
<br/>
{% ifequal shori '' %}
    <form method="post" enctype="multipart/form-data" action="{% url 'omoikane:menu_input' %}">
{% else %}
    <form method="post" enctype="multipart/form-data" action="{% url 'omoikane:menu_input_modify' id shori %}">
{% endifequal %}

    {% csrf_token %}
    {{form.menu_id}}

    {% ifequal shori '' %}
    <table class="simple_class">
        <tr>
            <th style="width:100px">{{form.menu_name.label}}</th>
            <td style="width:200px">{{form.menu_name}}{{form.menu_name.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.url.label}}</th>
            <td>{{form.url}}{{form.url.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.icon.label}}</th>
            <td>{{form.icon}}{{form.icon.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% ifequal shori 'm' %}
    <table class="simple_class">
        <tr>
            <th style="width:100px">{{form.menu_name.label}}</th>
            <td style="width:200px">{{form.menu_name}}{{form.menu_name.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.url.label}}</th>
            <td>{{form.url}}{{form.url.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.icon.label}}</th>
            <td>{{form.icon}}{{form.icon.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% ifequal shori 'd' %}
    <table class="simple_class">
        <tr>
            <th style="width:100px">{{form.menu_name.label}}</th>
            <td style="width:400px">{{form.id.}}{{form.menu_name}}{{form.menu_name.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.url.label}}</th>
            <td>{{form.url}}{{form.url.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.icon.label}}</th>
            <td>{{form.icon}}{{form.icon.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>
    <table id="controller">
        <tr>
            {% ifequal shori 'd' %}
                <td style="text-align:center;"><input type="submit" value="削除" class="square_btn" /></td>
            {% else %}
                <td style="text-align:center;"><input type="submit" value="登録" class="square_btn" /></td>
            {% endifequal %}
            <td style="text-align:center;"><input type="button" id="btn_cancel" value="キャンセル" class="square_btn" /></td>
        </tr>    
    </table>

{% endblock %}

templates/omoikane/menu_list.html
{% extends "omoikane/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/omoikane/user_input.js' %}" ></script>
{% endblock %}

{% block body %}
メニュ一覧<br/>
    
<form method="post" action="{% url 'omoikane:user_list' %}">
    {% csrf_token %}
    
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:750px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_class" style='width:300px'>メニュー名</th>
                        <th class="th_class" style='width:300px'>URL</th>
                        <th class="th_center_class" style='width:50px'>編集</th>
                        <th class="th_center_class" style='width:50px'>追加</th>
                        <th class="th_center_class" style='width:50px'>削除</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:400px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#BBBBBB">
            <table class="list_class">
                <tbody>
                    {% ifequal mmenus|length 0 %}
                    <tr id="row{{menu.id}}">
                        <td class="td_class" style='width:300px'><td>
                        <td class="td_class" style='width:300px'><td>
                        <td class="td_center_class" style='width:50px'><td>
                        <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:menu_input'  %}" >＋</a><td>
                        <td class="td_center_class" style='width:50px'><td>
                    </tr>
                    {% else %}
                        {% for menu in mmenus %}
                        <tr id="row{{menu.id}}">
                            <td class="td_class" style='width:300px'>{{menu.menu_name}}<td>
                            <td class="td_class" style='width:300px'>{{menu.url}}<td>
                            <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:menu_input_modify' menu.id 'm' %}" >...</a><td>
                            <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:menu_input'  %}" >＋</a><td>
                            <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:menu_input_modify' menu.id 'd' %}" >ー</a><td>
                        </tr>
                        {% endfor %}
                    {% endifequal %}
                </tbody>
            </table>
        </div>
    </div>
    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>

{% endblock %}

templates/omoikane/user_list.html
{% extends "omoikane/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/omoikane/user_input.js' %}" ></script>
{% endblock %}

{% block body %}
ユーザ一覧<br/>
    
<form method="post" action="{% url 'omoikane:user_list' %}">
    {% csrf_token %}
    
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:750px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_class" style='width:300px'>ユーザ名</th>
                        <th class="th_class" style='width:300px'>ユーザID</th>
                        <th class="th_center_class" style='width:50px'>編集</th>
                        <th class="th_center_class" style='width:50px'>追加</th>
                        <th class="th_center_class" style='width:50px'>削除</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:400px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#BBBBBB">
            <table class="list_class">
                <tbody>
                {% for user in musers %}
                    <tr id="row{{user.id}}">
                        <td class="td_class" style='width:300px'>{{user.user_name}}<td>
                        <td class="td_class" style='width:300px'>{{user.user_id}}</td>
                        <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:user_input_modify' user.user_id 'm' %}" >...</a><td>
                        <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:user_input'  %}" >＋</a><td>
                        <td class="td_center_class" style='width:50px'><a href="{% url 'omoikane:user_input_modify' user.user_id 'd' %}" >ー</a><td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>

{% endblock %}