izanagi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('susanowo/', include('susanowo.urls')),
    path('guestboard/', include('guestboard.urls')), 
    # url(r'^guestboard/', include(('guestboard.urls', 'guestboard'),)), 
    # path('uploader/', include('uploader.urls')), 
    url(r'^uploader/', include('uploader.urls')), 
    path('omoikane/', include('omoikane.urls')),
    path('tukuyomi/', include('tukuyomi.urls')),
    path('amaterasu/', include('amaterasu.urls')),
    path('amenouzume/', include('amenouzume.urls')),
    path('sarutahiko/', include('sarutahiko.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tukuyomi/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "tukuyomi"
urlpatterns = [
    url(r'^$', views.loginView.login, name='login'),
    url(r'^menu/$', views.menuView.menu, name='menu'),
    url(r'^assert_list/$', views.assertView.assert_list, name='assert_list'),
    url(r'^assert_input/$', views.assertView.assert_input, name='assert_input'),
    path('assert_input_modify/<int:id>/<str:shori>', views.assertView.assert_input_modify, name='assert_input_modify'),
    url(r'^buyer_list/$', views.buyerView.buyer_list, name='buyer_list'),
    url(r'^buyer_input$', views.buyerView.buyer_input, name='buyer_input'),
    path('buyer_input_modify/<int:id>/<str:shori>', views.buyerView.buyer_input_modify, name='buyer_input_modify'),
    url(r'^riyou_info_init/$', views.riyouView.riyou_info_init, name='riyou_info_init'),
    path('riyou_info/<int:y>/<int:m>', views.riyouView.riyou_info, name='riyou_info'),
    path('shiharai_info/<int:y>/<int:m>/<int:assert_cd>', views.shiharaiView.shiharai_info, name='shiharai_info'),
    # url(r'^shiharaih_input/$', views.shiharaihView.shiharaih_input, name='shiharaih_input'),
    path('shiharaih_input/<int:assert_cd>', views.shiharaihView.shiharaih_input, name='shiharaih_input'),
    path('shiharaih_input_modify/<int:shiharaih_id>/<str:shori>', views.shiharaihView.shiharaih_input_modify, name='shiharaih_input_modify'),
    path('shiharaim_input/<int:assert_cd>/<int:y>/<int:m>/<int:d>/<str:shop_name>', views.shiharaimView.shiharaim_input, name='shiharaim_input'),
    # path('shiharaim_insert/<int:assert_cd>/<int:y>/<int:m>/<int:d>/<str:shop_name>/<int:insert_row>', views.shiharaimView.shiharaim_insert, name='shiharaim_insert'),
    # path('shiharaim_delete/<int:assert_cd>/<int:y>/<int:m>/<int:d>/<str:shop_name>/<int:delete_row>', views.shiharaimView.shiharaim_delete, name='shiharaim_delete'),
    url(r'^henkin_header/$', views.henkinView.henkin_header, name='henkin_header'),
    url(r'^henkin_list/$', views.henkinView.henkin_list, name='henkin_list'),
    # url(r'^henkin_input/$', views.henkinView.henkin_input, name='henkin_input'),
]

tukuyomi/models/tshiharaih.py
from django.db import models
from django.db.models.signals import post_delete
from django.utils.timezone import now
from django.dispatch import receiver

class TShiharaiH(models.Model):

    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    used_date = models.DateField(
        verbose_name='利用日',
        blank=False,
    )

    shop_name = models.CharField(
        verbose_name='店名',
        max_length=30,
        blank=False,
    )

    assert_cd = models.IntegerField(
        verbose_name='資産名コード',
        blank=False,
    )

    used_amt = models.IntegerField(
        verbose_name='利用金額',
        blank=False,
    )

    receipt = models.ImageField(
        verbose_name='レシート',
        max_length=30,
        blank=True,
    )

    create_date = models.DateTimeField(
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

    update_date = models.DateTimeField(
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

    def __str__(self):
        """ファイルのURLを返す"""
        return self.receipt.url

# モデル削除後に`file_field`を削除する。
@receiver(post_delete, sender=TShiharaiH)
def delete_file(sender, instance, **kwargs):
    instance.receipt.delete(False)

tukuyomi/forms/assertForm.py
from django import forms
from django.forms import formsets
from django.forms import models
from tukuyomi.models.massert import MAssert

class AssertModelForm(forms.ModelForm):

    class Meta:
        model = MAssert
        fields = ('id','assert_nm')
        widgets = {
            'assert_nm': forms.TextInput(),
        }

# AssertListModelFormSet = formsets.formset_factory(form=AssertModelForm, extra=0,)

tukuyomi/forms/buyerForm.py
from django import forms
from django.forms import formsets
from django.forms import models
from tukuyomi.models.mbuyer import MBuyer

class BuyerModelForm(forms.ModelForm):

    class Meta:
        model = MBuyer
        fields = ('id','buyerNm')
        widgets = {
            'buyerNm': forms.TextInput(),
        }

tukuyomi/forms/loginForm.py
from django import forms
from django.forms import formsets
from django.forms import models
from omoikane.models import MUser

class LoginModelForm(forms.ModelForm):

    class Meta:
        model = MUser
        fields = ('user_id','password')
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

    def clean(self):
        cleaned_data = super().clean()
        v_user_id = cleaned_data.get('user_id') 
        v_password = cleaned_data.get('password')
        user = None
        try:
            user = MUser.objects.get(user_id=v_user_id)
        except:
            raise forms.ValidationError("ユーザIDが存在しません。")

        if not user.password==v_password:
            raise forms.ValidationError("パスワードが違います。")

        return cleaned_data

tukuyomi/views/assertView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from datetime import datetime, date, timedelta
from django import forms
# import datetime
import logging
import os
from tukuyomi.models.massert import MAssert
from tukuyomi.forms.assertForm import AssertModelForm

def assert_list(request):
    # AssertListModelFormSet = forms.modelformset_factory(
    #     MAssert,
    #     fields = ('id','assertNm'),
    # )
    
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

        # formSet = AssertListModelFormSet(queryset=MAssert.objects.filter(user_id=user_id).order_by('assertNm'))
        massert = MAssert.objects.filter(user_id=user_id).order_by('assert_nm')

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': massert,
            'now_year':datetime.strftime(datetime.now(), '%Y'),
            'now_month':datetime.strftime(datetime.now(), '%m'),
        }

        return render(request, 'tukuyomi/assert_list.html',context)

def assert_input(request):
    user_id = request.session.get('LOGIN_USER_ID')
    user_name = request.session.get('LOGIN_USER_NAME')

    if request.method == 'GET':
        form = AssertModelForm(request.GET or None)

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': form,
            'shori': '',
        }
        return render(request, 'tukuyomi/assert_input.html',context)
    
    elif request.method == 'POST':
        form = AssertModelForm(request.POST or None)
        if form.is_valid():
            massert = form.save(commit=False)
            massert.user_id = user_id
            massert.create_pg_id   = 'assert_input'
            massert.create_user_id = user_id
            massert.update_pg_id   = 'assert_input'
            massert.update_user_id = user_id
            massert.save()
            return redirect('/tukuyomi/assert_list/')
        else:
            context = {
                'user_id':user_id,
                'user_name':user_name,
                'form': form,
                'shori': '',
                'now_year':datetime.strftime(datetime.now(), '%Y'),
                'now_month':datetime.strftime(datetime.now(), '%m'),
            }
            return render(request, 'tukuyomi/assert_input.html',context)

def assert_input_modify(request,id,shori):
    user_id = request.session.get('LOGIN_USER_ID')
    user_name = request.session.get('LOGIN_USER_NAME')

    if request.method == 'GET':
        massert = MAssert.objects.get(id=id)
        form = AssertModelForm(request.GET or None,instance=massert)

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': form,
            'shori': shori,
            'id': id,
            'now_year':datetime.strftime(datetime.now(), '%Y'),
            'now_month':datetime.strftime(datetime.now(), '%m'),
        }
        return render(request, 'tukuyomi/assert_input.html',context)
    
    elif request.method == 'POST':
        form = AssertModelForm(request.POST)
        if form.is_valid():
            massert = form.save(commit=False)
            massert = get_object_or_404(MAssert, id=id)
            if shori=='m':
                massert.assert_nm       = request.POST['assertNm']
                massert.update_date    = timezone.datetime.now()
                massert.update_pg_id   = 'assert_input'
                massert.update_user_id = user_id
                massert.save()
            elif shori=='d':
                massert.delete()
            return redirect('/tukuyomi/assert_list/')
        else:
            context = {
                'user_id':user_id,
                'user_name':user_name,
                'form': form,
                'shori':shori,
                'id': id,
                'now_year':datetime.strftime(datetime.now(), '%Y'),
                'now_month':datetime.strftime(datetime.now(), '%m'),
            }
            return render(request, 'tukuyomi/assert_input.html',context)

tukuyomi/views/buyerView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from datetime import datetime, date, timedelta
from django import forms
# import datetime
import logging
import os
from tukuyomi.models.mbuyer import MBuyer
from tukuyomi.forms.buyerForm import BuyerModelForm

def buyer_list(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

        mbuyer = MBuyer.objects.filter(user_id=user_id).order_by('buyerNm')

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': mbuyer,
            'now_year':datetime.strftime(datetime.now(), '%Y'),
            'now_month':datetime.strftime(datetime.now(), '%m'),
        }

        return render(request, 'tukuyomi/buyer_list.html',context)

def buyer_input(request):
    user_id = request.session.get('LOGIN_USER_ID')
    user_name = request.session.get('LOGIN_USER_NAME')

    if request.method == 'GET':
        form = BuyerModelForm(request.GET or None)

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': form,
            'shori': '',
            'now_year':datetime.strftime(datetime.now(), '%Y'),
            'now_month':datetime.strftime(datetime.now(), '%m'),
        }
        return render(request, 'tukuyomi/buyer_input.html',context)
    
    elif request.method == 'POST':
        form = BuyerModelForm(request.POST or None)
        if form.is_valid():
            mbuyer = form.save(commit=False)
            mbuyer.user_id = user_id
            mbuyer.create_pg_id   = 'buyer_input'
            mbuyer.create_user_id = user_id
            mbuyer.update_pg_id   = 'buyer_input'
            mbuyer.update_user_id = user_id
            mbuyer.save()
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id':user_id,
                'user_name':user_name,
                'form': form,
                'shori': '',
                'now_year':datetime.strftime(datetime.now(), '%Y'),
                'now_month':datetime.strftime(datetime.now(), '%m'),
            }
            return render(request, 'tukuyomi/menu.html',context)

def buyer_input_modify(request,id,shori):
    user_id = request.session.get('LOGIN_USER_ID')
    user_name = request.session.get('LOGIN_USER_NAME')

    if request.method == 'GET':
        mbuyer = MBuyer.objects.get(id=id)
        form = BuyerModelForm(request.GET or None,instance=mbuyer)

        context = {
            'user_id':user_id,
            'user_name':user_name,
            'form': form,
            'shori': shori,
            'id': id,
            'now_year':datetime.strftime(datetime.now(), '%Y'),
            'now_month':datetime.strftime(datetime.now(), '%m'),
        }
        return render(request, 'tukuyomi/buyer_input.html',context)
    
    elif request.method == 'POST':
        form = BuyerModelForm(request.POST)
        if form.is_valid():
            mbuyer = form.save(commit=False)
            mbuyer = get_object_or_404(MBuyer, id=id)
            if shori=='m':
                mbuyer.buyerNm        = request.POST['buyerNm']
                mbuyer.update_date    = timezone.datetime.now()
                mbuyer.update_pg_id   = 'buyer_input'
                mbuyer.update_user_id = user_id
                mbuyer.save()
            elif shori=='d':
                mbuyer.delete()
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id':user_id,
                'user_name':user_name,
                'form': form,
                'shori':shori,
                'id': id,
                'now_year':datetime.strftime(datetime.now(), '%Y'),
                'now_month':datetime.strftime(datetime.now(), '%m'),
            }
            return render(request, 'tukuyomi/menu.html',context)

tukuyomi/views/loginView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
import logging
import os
from izanagi import settings
from tukuyomi.forms.loginForm import LoginModelForm
from omoikane.models import MUser

def login(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        form = LoginModelForm(request.GET or None)
        context = {
            'form': form
        }

        if user_id:
            return redirect('/tukuyomi/menu/')

        return render(request, 'tukuyomi/login.html',context)

    elif request.method == 'POST':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        if user_id is None:
            user_id = request.POST['user_id']
            user = MUser.objects.get(user_id=user_id)
            user_name = user.user_name
            request.session['LOGIN_USER_ID'] = user.user_id
            request.session['LOGIN_USER_NAME'] = user.user_name

        form = LoginModelForm(request.POST)
        if form.is_valid():
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id': user_id,
                'user_name': user_name,
                'form': form,
            }
            return render(request, 'tukuyomi/login.html', context)

tukuyomi/views/menuView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
    reverse,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
from datetime import datetime
import logging
import os
from tukuyomi import tukuyomiConst
from tukuyomi.models.mbuyer import MBuyer

def menu(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

    # 定数初期化
    mbuyers = MBuyer.objects.filter(user_id=user_id).order_by('buyerNm')
    tukuyomiConst.BUYER_CHOICE = []
    tukuyomiConst.BUYER_CHOICE.append((None, ''))
    for buyer in mbuyers:
        tukuyomiConst.BUYER_CHOICE.append((buyer.id, buyer.buyerNm))

    context = {
        'user_id':user_id,
        'user_name':user_name,
        'now_year':datetime.strftime(datetime.now(), '%Y'),
        'now_month':datetime.strftime(datetime.now(), '%m'),
        # 'now_year':datetime.strftime(datetime.today(), '%Y'),
        # 'now_month':datetime.strftime(datetime.today(), '%m'),
        'form': None,
    }

    return render(request, 'tukuyomi/menu.html',context)

templates/tukuyomi/assert_list.html
{% extends "tukuyomi/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/tukuyomi/assert_input.js' %}" ></script>
{% endblock %}

{% block body %}
<div class="title_class">
    資産名一覧<br/><br/>
</div>
    
<form method="post" action="{% url 'tukuyomi:assert_list' %}">
    {% csrf_token %}
    
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:550px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_header th_center_class" style='width:400px'>資産名</th>
                        <th class="th_header th_center_class" style='width:50px'>編集</th>
                        <th class="th_header th_center_class" style='width:50px'>追加</th>
                        <th class="th_header th_center_class" style='width:50px'>削除</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:100%; width:100%;overflow-y:scroll;overflow-x:hidden;">
            <table class="list_class">
                <tbody>
                    {% ifequal form|length 0 %}
                    <tr class="tr_class" id="row{{menu.id}}">
                        <td class="td_class" style='width:400px'><td>
                        <td class="td_center_class" style='width:50px'><td>
                        <td class="td_center_class" style='width:50px'>
                            <a href="{% url 'tukuyomi:assert_input' %}" >
                                <img src="{% static 'png/common/insert.png' %}"/>
                            </a>
                        <td>
                        <td class="td_center_class" style='width:50px'><td>
                    </tr>
                    {% else %}
                        {% for assert in form %}
                        <tr class="tr_class" id="row{{assert.id}}">
                            <td class="td_class" style='width:400px'>{{assert.assert_nm}}<td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:assert_input_modify' assert.id 'm' %}" >
                                    <img src="{% static 'png/common/edit.png' %}"/>
                                </a>
                            <td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:assert_input' %}" >
                                    <img src="{% static 'png/common/insert.png' %}"/>
                                </a>
                            <td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:assert_input_modify' assert.id 'd' %}" >
                                    <img src="{% static 'png/common/delete.png' %}"/>
                                </a>
                            <td>
                        </tr>
                        {% endfor %}
                    {% endifequal %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/tukuyomi/base.html
{% load static %}
<!DOCTYPE himl>
<html>
    <head lang='ja'>
    <meta charset='UTF-8'>
    <title>
        電子マネー管理
    </title>
    <LINK rel="shortcut icon" href="{% static 'icon/tukuyomi.ico' %}">
    <link rel="stylesheet" href="{% static 'css/tukuyomi/tukuyomi.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" >
    <script src="{% static 'js/bootstrap.js' %}" ></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
    <script src="{% static 'js/jquery-ui.js' %}" ></script>
    <script src="{% static 'js/common.js' %}" ></script>
    {% block header %}
    {% endblock %}
</head>
<body>
    {{message}}
    <table style="width:100%;height:100%;">
        <tbody>
            <tr>
                <th style="width:150px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'tukuyomi:menu' %}">
                        <img src="{% static 'icon/tukuyomi.ico' %}"/><br/>
                        電子マネー管理
                    </a>
                </th>
                <td style="text-align:center; width:150px;" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'tukuyomi:riyou_info' now_year now_month %}" >
                        <img src="{% static 'png/tukuyomi/useinfo.png' %}"/><br/>
                        利用者情報<br/>
                    </a>
                </td>
                <td style="text-align:center; width:150px;" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'tukuyomi:assert_list' %}" >
                        <img src="{% static 'png/tukuyomi/assert.png' %}"/><br/>
                        資産名<br/>    
                    </a>
                </td>
                <td style="text-align:center; width:150px;" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'tukuyomi:buyer_list' %}" >
                        <img src="{% static 'png/tukuyomi/buyer.png' %}"/><br/>
                        購入者<br/>
                    </a>
                </td>
                <td style="text-align:center; width:150px;" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'tukuyomi:henkin_header' %}" >
                        <img src="{% static 'png/tukuyomi/refund.png' %}"/><br/>
                        返金<br/>
                    </a>
                </td>
                <td style="text-align:right; width:auto" class="menu th_center_class">
                    {{user_id}}({{user_name}})<br/><br/>
                    <a class="menu_class" href="/tukuyomi/">ログアウト</a>
                </td>
            </tr>
            <tr>
                <td class="main_body" colspan="6">
                    {% block body %}
                    {% endblock %}
                </td>
            </tr>
        </tbody>
    </table>
    <br/>
    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>

</body>
</html>

templates/tukuyomi/buyer_list.html
{% extends "tukuyomi/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/tukuyomi/buyer_input.js' %}" ></script>
{% endblock %}

{% block body %}
<div class="title_class">
    購入者一覧<br/><br/>
</div>
    
<form method="post" action="{% url 'tukuyomi:buyer_list' %}">
    {% csrf_token %}
    
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:550px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_header th_center_class" style='width:400px'>購入者</th>
                        <th class="th_header th_center_class" style='width:50px'>編集</th>
                        <th class="th_header th_center_class" style='width:50px'>追加</th>
                        <th class="th_header th_center_class" style='width:50px'>削除</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:100%; width:100%;overflow-y:scroll;overflow-x:hidden;">
            <table class="list_class">
                <tbody>
                    {% ifequal form|length 0 %}
                    <tr class="tr_class" id="row{{menu.id}}">
                        <td class="td_class" style='width:400px'><td>
                        <td class="td_center_class" style='width:50px'><td>
                        <td class="td_center_class" style='width:50px'>
                            <a href="{% url 'tukuyomi:buyer_input' %}" >
                                <img src="{% static 'png/common/insert.png' %}"/>
                            </a>
                        <td>
                        <td class="td_center_class" style='width:50px'><td>
                    </tr>
                    {% else %}
                        {% for buyer in form %}
                        <tr class="tr_class" id="row{{buyer.id}}">
                            <td class="td_class" style='width:400px'>{{buyer.buyerNm}}<td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:buyer_input_modify' buyer.id 'm' %}" >
                                    <img src="{% static 'png/common/edit.png' %}"/>
                                </a>
                            <td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:buyer_input' %}" >
                                    <img src="{% static 'png/common/insert.png' %}"/>
                                </a>
                            <td>
                            <td class="td_center_class" style='width:50px'>
                                <a href="{% url 'tukuyomi:buyer_input_modify' buyer.id 'd' %}" >
                                    <img src="{% static 'png/common/delete.png' %}"/>
                                </a>
                            <td>
                        </tr>
                        {% endfor %}
                    {% endifequal %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/tukuyomi/menu.html
{% extends "tukuyomi/base.html" %}

{% load static %}
{% block header %}
{% endblock %}

{% block body %}
クレジットカード、電子マネーの予算管理、<br/>
利用状況の把握と立替金を管理します。<br/>
{% endblock %}

templates/tukuyomi/riyou_info.html
{% extends "tukuyomi/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/tukuyomi/riyou_info.js' %}" ></script>
{% endblock %}

{% block body %}
<div class="title_class">
    利用者情報<br/><br/>
</div>
    
<form method="post" action="{% url 'tukuyomi:assert_list' %}">
    {% csrf_token %}
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:550px; border-style:solid;border-width:0px; text-align: center;">
        <a class="normal_class" id="minus_month" href="{% url 'tukuyomi:riyou_info' next_prev.prev_y next_prev.prev_m %}" >＜</a>
        　{{used_year}}/{{used_month}}　
        <a class="normal_class" id="plus_month" href="{% url 'tukuyomi:riyou_info' next_prev.next_y next_prev.next_m %}" >＞</a>
        <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_header th_center_class " style='width:400px'>資産名</th>
                        <th class="th_header th_right_class" style='width:200px'>金額</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:100%; width:100%;overflow-y:scroll;overflow-x:hidden;">
            <table class="list_class">
                <tbody>
                    {% for rec in form %}
                    <tr class="tr_class" id="row{{assert.id}}">
                        <td class="td_class" style='width:400px'>
                            <a class="normal_class" href="{% url 'tukuyomi:shiharai_info' used_year used_month rec.assert_id %}" >
                                {{rec.assert_nm}}
                            </a>
                        </td>
                        <td class="td_right_class" style='width:200px'>
                            {{rec.sum_amt}}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</form>
{% endblock %}