izanagi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('susanowo/', include('susanowo.urls')),
    path('guestboard/', include('guestboard.urls')), 
    # url(r'^guestboard/', include(('guestboard.urls', 'guestboard'),)), 
    # path('uploader/', include('uploader.urls')), 
    url(r'^uploader/', include('uploader.urls')), 
    path('omoikane/', include('omoikane.urls')),
    path('tukuyomi/', include('tukuyomi.urls')),
    path('amaterasu/', include('amaterasu.urls')),
    path('amenouzume/', include('amenouzume.urls')),
    path('sarutahiko/', include('sarutahiko.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

susanowo/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "susanowo"
urlpatterns = [
    url(r'^$', views.indexviews.login, name='login'),
    url(r'^index/$', views.indexviews.index, name='index'),
    url(r'^inbox/$', views.inboxviews.newInbox, name='inbox'),
    url(r'^inboxupd/$', views.inboxviews.inboxAdd, name='inboxupd'),
    url(r'^modstatus/$', views.indexviews.modstatus, name='modstatus'),
    path('inbox/<int:todo_id>', views.inboxviews.inbox, name='inbox'),
    path('inboxupd/<int:todo_id>', views.inboxviews.inboxUpd, name='inboxupd'),
    url(r'^gomibako/$', views.gomiviews.gomibakoList, name='gomibako'),
    url(r'^gomisakujo/$', views.gomiviews.gomiSakujo, name='gomisakujo'),
    # path('shiryou/<int:todo_id>', views.shiryouviews.shiryouList, name='shiryou'),
    path('shiryou/<int:todo_id>', views.shiryouviews.multi_upload_with_model, name='shiryou'),
    # path('shiryouupd/<int:todo_id>', views.shiryouviews.shiryouupd, name='shiryouupd'),
    # path('delete_file/<int:id>', views.shiryouviews.delete_file, name='delete_file'),
    url(r'^delete_file/$', views.shiryouviews.delete_file, name='delete_file'),
    url(r'^shiryou_list/$', views.shiryouviews.shiryou_list, name='shiryou_list'),
    url(r'^shiryou_delete/$', views.shiryouviews.shiryou_delete, name='shiryou_delete'),
]

omoikane/models.py
from django.db import models
from django.utils.timezone import now
from django.shortcuts import render

# Create your models here.
class MUser(models.Model):
    user_id = models.CharField(
        verbose_name='ユーザID',
        max_length=30,
        help_text='システムにログインするIDを入力してください',
        blank=False,
    )
    user_name = models.CharField(
        verbose_name='ユーザ名',
        max_length=30,
        help_text='お名前を入力してください',
        default=''
    )
    password = models.CharField(
        verbose_name='パスワード',
        max_length=30,
        help_text='システムにログインするパスワードを入力してください',
        blank=False,
    )
    admin_auth = models.BooleanField(
        verbose_name='管理者権限',
        blank=False,
        default=False,
    )
    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )
    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )
    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )
    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

def get_upload_dir(instance, filename):
    return 'omoikane/icon/{0}/{1}'.format(instance.id,instance.icon)

class MMenu(models.Model):
    id = models.AutoField(
        primary_key=True,
        verbose_name='メニューID',
    )
    menu_name = models.CharField(
        verbose_name='メニュー名称',
        max_length=50,
        help_text='システム名を入力してください',
        blank=False,
        default=''
    )
    url = models.CharField(
        verbose_name='URL',
        max_length=100,
        help_text='システムのURLを入力してください',
        blank=False,
        default=''
    )
    icon = models.ImageField(
        verbose_name='リンクアイコン',
        upload_to=get_upload_dir,
        blank=True,
        null=True,
    )
    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )
    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )
    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )
    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

class MAuth(models.Model):
    user_id = models.CharField(
        verbose_name='ユーザID',
        max_length=30,
        help_text='システムにログインするIDを入力してください',
        blank=False,
    )

    menu_id = models.CharField(
        verbose_name='メニューID',
        max_length=30,
        blank=True,
    )

susanowo/models/ttodo.py
from django.db import models
from django.utils.timezone import now

WHERE_DONT_ACTION = (
    ('1','いつかやる'),
    ('2','参考資料'),
    ('3','ごみ箱')
)

CATEGORY = {
    '06':'いつかやる',
    '07':'参考資料',
    '08':'ゴミ箱',
    '02':'プロジェクト',
    '01':'すぐやる',
    '05':'他人に任せる',
    '04':'特定の日にやる',
    '03':'自分でやる',
}

class TTodo(models.Model):
    # todo_id = models.AutoField(
    #     primary_key=True
    # )  # 自動的に追加されるので定義不要
    title = models.CharField(
        verbose_name='タイトル',
        max_length=30,
        help_text='タスクのタイトルを入力してください',
    )
    discription = models.TextField(
        verbose_name='タスクの詳細',
        help_text='タスクの詳細な内容を入力して下さい',
    )
    should_action = models.BooleanField(
        verbose_name='行動を起こす必要があるか？',
        blank=True,
    )
    action_selection = models.CharField(
        verbose_name='行動しない場合',
        max_length=1,
        choices=WHERE_DONT_ACTION,
        blank=True,
    )
    delivery_date = models.DateField(
        verbose_name='期限',
        blank=True,
        null=True,
    )
    single_action = models.BooleanField(
        verbose_name='アクションは１つ？',
        blank=True,
    )
    can_do_tow_minite = models.BooleanField(
        verbose_name='２分以上かかりそう？',
        blank=True,
    )
    should_myself = models.BooleanField(
        verbose_name='自分でやるべき',
        blank=True,
    )
    should_do_oneday = models.BooleanField(
        verbose_name='特定の日にやるべき？',
        blank=True,
    )
    date_should_do = models.DateField(
        verbose_name='実行日',
        blank=True,
        null=True,
    )
    user_id = models.CharField(
        verbose_name='ログインID',
        max_length=6,
        blank=True,
    )
    category = models.CharField(
        verbose_name='カテゴリー',
        max_length=2,
        blank=True,
    )
    completed = models.BooleanField(
        verbose_name='完了',
        blank=True,
        default=False,
    )
    deleted = models.BooleanField(
        verbose_name='削除',
        blank=True,
        default=False,
    )
    request_pertner = models.CharField(
        verbose_name='依頼した人',
        help_text='自分で行わない場合、依頼した人を入力して下さい。',
        max_length=200,
        blank=True,
    )
    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )
    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    create_user_id = models.CharField(
        max_length=6,
        blank=True,
    )
    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )
    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )
    update_user_id = models.CharField(
        max_length=6,
        blank=True,
    )

    def category_name(self):
        if self.category in CATEGORY:
            return CATEGORY[self.category]
        else:
            return ''
    
    def isCompleted(self):
        if self.completed==1:
            return 'checked'
        else:
            return ''

    def isDeleted(self):
        if self.deleted==1:
            return 'checked'
        else:
            return ''

def computeCategory(todo):
    category = '99'
    if todo.should_action:
        if todo.single_action:
            category = '02'

        if not todo.can_do_tow_minite:
            category = '01'

        if todo.should_myself:
            category = '03'
        else:
            category = '05'

        if todo.should_do_oneday:
            category = '04'

    else:
        if todo.action_selection == '1':
            category = '06'
        elif todo.action_selection == '2':
            category = '07'
        elif todo.action_selection == '3':
            category = '08'

    return category

susanowo/forms/inboxForm.py
from django import forms
from susanowo.models.ttodo import TTodo

WHERE_DONT_ACTION = (
    ('1','いつかやる'),
    ('2','参考資料'),
    ('3','ごみ箱')
)

class InboxForm(forms.Form):
    title = forms.CharField(
        label='タイトル',
        max_length=30,
        required=True,
        widget=forms.TextInput()
    )
    
    discription = forms.CharField(
        label='タスクの詳細',
        required=True,
        widget=forms.Textarea(attrs={'rows':4, 'cols':40})
    )

    should_action = forms.BooleanField(
        label='行動を起こす必要があるか？',
        required=False,
    )
    
    where_dont_action = forms.ChoiceField(
        label='',
        widget=forms.RadioSelect,
        choices=WHERE_DONT_ACTION,
        required=True,
    )
    
    single_action = forms.BooleanField(
        label='アクションは１つ？',
        required=False,
    )
    
    can_do_tow_minite = forms.BooleanField(
        label='２分以内で終わる？',
        required=False,
    )
    
    should_myself = forms.BooleanField(
        label='自分でやるべき',
        required=False,
    )
    
    should_do_than_2min = forms.BooleanField(
        label='特定の日にやるべき？',
        required=False,
    )

susanowo/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.
def login(request):
    return HttpResponse('Hello susanowo')

def index(request):
    d = {
        'today': datetime.datetime.today().strftime("%Y/%m/%d")
    }
    return render(request, 'susanowo/index.html', d)

def inbox(request):
    return render(request, 'susanowo/inbox.html')

susanowo/views/gomiviews.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from susanowo.models.ttodo import TTodo
from susanowo.forms.inboxModelForm import InboxModelForm
import datetime

# Create your views here.
def gomibakoList(request):
    d = {
        'today': datetime.datetime.today().strftime("%Y/%m/%d"),
        'ttodos': TTodo.objects.filter(category='08').order_by('create_date'),
    }
    return render(request, 'susanowo/gomibako.html', d)

def gomiSakujo(request):
    # delete_list = request.POST.getlist()
    # delete_list = request.POST.lists()
    deleted_list = request.POST.getlist('deleted')
    # id_list = request.POST.getlist('id')
    for id in deleted_list:
        t_todo = TTodo.objects.get(id=id)
        t_todo.delete()

    return redirect('/susanowo/index')

susanowo/views/inbox_views.py
from django.shortcuts import render
from django.http import HttpResponse
from susanowo.forms.inboxForm import InboxForm

# Create your views here.
def inbox(request):
    form = InboxForm(request.GET or None)
    d = {
        'form':form,
    }
    return render(request, 'susanowo/inbox.html', d)

def inbox_submit(request):
    d = {
        'title': "",
        'discription': ""
    }
    return render(request, 'susanowo/index.html', d)

susanowo/views/inboxviews.py
from django.shortcuts import (
    render, 
    redirect, 
    get_object_or_404,
)
from django.http import HttpResponse
from susanowo.forms.inboxModelForm import InboxModelForm
from susanowo.models import ttodo
from susanowo.models.ttodo import TTodo
import datetime
import logging
# from susanowo.forms.inboxForm import InboxForm
# from susanowo.models.ttodo import TTodo

# Create your views here.
def inbox(request,todo_id):
    form = InboxModelForm(request.GET or None)
    # form = InboxModelForm{user_id="admin")
    if todo_id is not None :
        # id = request.GET.get("rownum")
        t_todo = TTodo.objects.get(id=todo_id)
        form = InboxModelForm(instance=t_todo)
    d = {
        'form':form,
        'todo_id':todo_id,
    }
    return render(request, 'susanowo/inbox.html', d)

def newInbox(request):
    form = InboxModelForm(request.GET or None)
    d = {
        'form':form,
        'todo_id':'',
    }
    return render(request, 'susanowo/inbox.html', d)

def inboxUpd(request,todo_id):
    todo = get_object_or_404(TTodo,id=todo_id)
    form = InboxModelForm(request.POST)
    if form.is_valid():
        todo.title             = form.cleaned_data['title']
        todo.discription       = form.cleaned_data['discription']
        todo.should_action     = form.cleaned_data['should_action']
        todo.action_selection  = form.cleaned_data['action_selection']
        todo.delivery_date     = form.cleaned_data['delivery_date']
        todo.single_action     = form.cleaned_data['single_action']
        todo.can_do_tow_minite = form.cleaned_data['can_do_tow_minite']
        todo.should_myself     = form.cleaned_data['should_myself']
        todo.should_do_oneday  = form.cleaned_data['should_do_oneday']
        todo.date_should_do    = form.cleaned_data['date_should_do']
        todo.request_pertner   = form.cleaned_data['request_pertner']
        todo.category          = ttodo.computeCategory(todo)
        todo.save()
        return redirect('/susanowo/index')
    else:
        d = {
            'form':form,
            'todo_id':todo_id,
        }
    return render(request, 'susanowo/indox.html', d)

def inboxAdd(request):
    mForm = InboxModelForm(request.POST)
    if mForm.is_valid():
        todo = mForm.save()
        todo.category = ttodo.computeCategory(todo)
        todo.save()
        return redirect('/susanowo/index')
    else:
        d = {
            'form':mForm,
            'todo_id':'',
        }
    return render(request, 'susanowo/indox.html', d)

susanowo/views/index_views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime

# Create your views here.
def login(request):
    return HttpResponse('Hello susanowo')

def index(request):
    d = {
        'today': datetime.datetime.today().strftime("%Y/%m/%d"),
    }
    return render(request, 'susanowo/index.html', d)

susanowo/views/indexviews.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from susanowo.models.ttodo import TTodo
from susanowo.forms.loginModelForm import MUserModelForm
from omoikane.models import MUser
import datetime

# Create your views here.
def login(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        form = MUserModelForm(request.GET or None)
        context = {
            'form': form
        }

        if user_id:
            return redirect('/susanowo/index')

        return render(request, 'susanowo/login.html', context)
    else:
        form = MUserModelForm(request.POST)
        if not form.is_valid():
            context = {
                'form': form
            }
            return render(request, 'susanowo/login.html', context)
        return redirect('/susanowo/index')

def requestLogin(request):

    return HttpResponse('Hello susanowo')

def index(request):
    d = {
        'today': datetime.datetime.today().strftime("%Y/%m/%d"),
        'ttodos': TTodo.objects.filter(~Q(category='07') & ~Q(category='08')).order_by('deleted','category','delivery_date'),
    }

    return render(request, 'susanowo/index.html', d)

def modstatus(request):
    if request.method == 'POST':
        id = request.POST.get('param_id')
        complete = request.POST.get('param_complete')
        delete = request.POST.get('param_delete')

        t_todo = TTodo.objects.get(id=id)
        t_todo.completed = complete
        t_todo.deleted = delete
        t_todo.save()

    return HttpResponse(t_todo)

tukuyomi/views/loginView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
import logging
import os
from izanagi import settings
from tukuyomi.forms.loginForm import LoginModelForm
from omoikane.models import MUser

def login(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        form = LoginModelForm(request.GET or None)
        context = {
            'form': form
        }

        if user_id:
            return redirect('/tukuyomi/menu/')

        return render(request, 'tukuyomi/login.html',context)

    elif request.method == 'POST':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        if user_id is None:
            user_id = request.POST['user_id']
            user = MUser.objects.get(user_id=user_id)
            user_name = user.user_name
            request.session['LOGIN_USER_ID'] = user.user_id
            request.session['LOGIN_USER_NAME'] = user.user_name

        form = LoginModelForm(request.POST)
        if form.is_valid():
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id': user_id,
                'user_name': user_name,
                'form': form,
            }
            return render(request, 'tukuyomi/login.html', context)

templates/susanowo/base.html
{% load static %}
<!DOCTYPE himl>
<html>
    <head lang='ja'>
    <meta charset='UTF-8'>
    <title>
        GTD
    </title>
    <link rel="stylesheet" href="{% static 'css/susanowo.css' %}" >
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" >
    <LINK rel="shortcut icon" href="{% static 'icon/susanowo.ico' %}">
    <script src="{% static 'js/bootstrap.js' %}" ></script>
    <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
    <script src="{% static 'js/jquery-ui.js' %}" ></script>
    <script src="{% static 'js/common.js' %}" ></script>
    {% block header %}
    {% endblock %}
</head>
<body>
    {{message}}
    {% block body %}
    {% endblock %}
</body>
</html>

templates/susanowo/inbox.html
{% extends "susanowo/base.html" %}

{% load static %}
{% block header %}
{% endblock %}

{% block body %}
<script src="{% static 'js/susanowo/inbox.js' %}" ></script>
<link rel="stylesheet" href="{% static 'css/susanowo/inbox.css' %}" >

<div id="header">
    インボックス
</div>
{% if todo_id == '' %}
<form method="post" action="{% url 'susanowo:inboxupd' %}">
{% else %}
<form method="post" action="{% url 'susanowo:inboxupd' todo_id %}">
{% endif %}
        {% csrf_token %}
    <input type="hidden" name="id" id="id_id" value="{{todo_id}}" />
    <table class="simple_class">
        <tr>
            <th style="width:250px">{{form.title.label}}</th>
            <td style="width:750px">{{form.title}}</td>
        </tr>
        <tr>
            <th>{{form.discription.label}}</th>
            <td>{{form.discription}}</li>
        </tr>
        <tr>
            <th>{{form.should_action.label}}</th>
            <td>{{form.should_action}}</td>
        </tr>
        <tr>
            <th>{{form.action_selection.label}}</th>
            <td>{{form.action_selection}}</td>
        </tr>
        <tr>
            <th>{{form.delivery_date.label}}</th>
            <td>{{form.delivery_date}}</td>
            <script>
                $(function () {
                    // 日付は、年-月-日 の形式でお願いする。
                    let dateFormat = 'yy-mm-dd';
                    $('#id_delivery_date').datepicker({
                        dateFormat: dateFormat,
                        defaultDate: null,
                    });
                });
            </script>
        </tr>
        <tr>
            <th>{{form.single_action.label}}</th>
            <td>{{form.single_action}}</td>
        </tr>
        <tr>
            <th>{{form.can_do_tow_minite.label}}</th>
            <td>{{form.can_do_tow_minite}}</td>
        </tr>
        <tr>
            <th>{{form.should_myself.label}}</th>
            <td>{{form.should_myself}}</td>
        </tr>
        <tr>
            <th>{{form.request_pertner.label}}</th>
            <td>{{form.request_pertner}}</td>
        </tr>
        <tr>
            <th>{{form.should_do_oneday.label}}</th>
            <td>{{form.should_do_oneday}}</yd>
        </tr>
        <tr>
            <th>{{form.date_should_do.label}}</th>
            <td>{{form.date_should_do}}</td>
            <script>
                $(function () {
                    // 日付は、年-月-日 の形式でお願いする。
                    let dateFormat = 'yy-mm-dd';
                    $('#id_date_should_do').datepicker({
                        dateFormat: dateFormat,
                        defaultDate: null,
                    });
                });
            </script>
        </tr>
    </table>

    <table id="controller">
        <tr>
            <td style="width:500px;text-align:center;"><input type="submit" value="登録" class="square_btn" /></td>
            <td style="width:500px;text-align:center;"><a href="/susanowo/index" class="square_btn">キャンセル</a></td>
        </tr>    
    </table>

</form>
{% endblock %}

templates/susanowo/index.html
{% extends "susanowo/base.html" %}

{% load static %}
{% block body %}
<script src="{% static 'js/susanowo/index.js' %}" ></script>
<form method="post" action="{% url 'susanowo:modstatus' %}" id="modstatus">
    {% csrf_token %}
    <input type="hidden" id="param_id" name="param_id" value="" />
    <input type="hidden" id="param_complete" name="param_complete" value="" />
    <input type="hidden" id="param_delete" name="param_delete" value="" />
</form>

    <div id="header" style="position: relative; top: 10px; left:400px; height:10px;">
        Getting Things Done
    </div>

    <div id="menu" style="position: relative; top: 50px; left:10px; width: 170px; height: 20px;">
        <ul class="menu_list">
            <li><a href="{% url 'susanowo:inbox' %}" class="square_btn">インボックス</a></li>
            <li><a href="{% url 'susanowo:shiryou_list' %}" class="square_btn">参考資料</a></li>
            <li><a href="{% url 'susanowo:gomibako' %}" class="square_btn">ゴミ箱</a></li>
        </ul>
    </div>

    <div id="todo_list" style="position:absolute; top:50px; left:240px;">
        <div id="gtd_date" style="position: relative; top: 0px; left:0px; width: 200px;">
            {{today}}
        </div>

        <!-- ========== テーブル全体を表す div ========== -->
        <div style="width:1000px; border-style:solid;border-width:1px;">
        <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
            <div style="width:100%">
                <table class="list_class">
                    <thead>
                        <tr>
                            <th class="th_class" style='width:50px'>完了</th>
                            <th class="th_class" style='width:150px'>アクション</th>
                            <th class="th_class" style='width:100px'>期限</th>
                            <th class="th_class" style='width:200px'>タイトル</th>
                            <th class="th_class" style='width:400px'>内容</th>
                            <th class="th_class" style='width:50px'>編集</th>
                            <th class="th_class" style='width:50px'>削除</th>
                            <th class="th_class" style='width:50px'>添付</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
            <div style="height:400px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#BBBBBB">
                <table class="list_class">
                    <tbody>
                        {% for todo in ttodos %}
                        <tr id="row{{todo.id}}" class="normal_row">
                            <td class="checkbox_class" style='width:50px'><input id="completed_{{todo.id}}" class="checkbox_class" type="checkbox" onchange="updStatus({{todo.id}})" {{todo.isCompleted}} /></td>
                            <td style='width:150px'>{{todo.category_name}}<td>
                            <td class="date_class" style='width:100px'>{{todo.delivery_date|date:"Y/m/d"}}</td>
                            <td style='width:200px'>{{todo.title}}<td>
                            <td style='width:400px'>{{todo.discription}}<td>
                            <td style='width:50px'><a href="{% url 'susanowo:inbox' todo.id %}" >編集</a><td>
                            <td class="checkbox_class" style='width:50px'><input id="delete_{{todo.id}}" class="checkbox_class" type="checkbox" onchange="updStatus({{todo.id}})" {{todo.isDeleted}} /><td>
                            <td style='width:50px'><a href="{% url 'susanowo:shiryou' todo.id %}" >資料</a><td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
            
    </div>
{% endblock %}

templates/susanowo/login.html
{% extends "susanowo/base.html" %}

{% load static %}
{% block body %}
<script src="{% static 'js/susanowo/inbox.js' %}" ></script>
<link rel="stylesheet" href="{% static 'css/susanowo/inbox.css' %}" >

<div id="" style="position: relative; top: 10px; left:400px; height:10px;">

<div id="header">
    GTD ログイン<br/>
    <br/>
</div>
<form method="post" action="{% url 'susanowo:login' %}" id="modstatus">
    {% csrf_token %}
    <table class="simple_class">
        <tr>
            <th style="width:50px">{{form.user_id.label}}</th>
            <td style="width:200px">{{form.user_id}}{{form.user_id.errors.0}}</td>
        </tr>
        <tr>
            <th>{{form.password.label}}</th>
            <td>{{form.password}}{{form.user_id.errors.0}}</td>
        </tr>
    </table>
    {% if form.non_field_errors %}
    <div class="ui red message">
        <ul class="menu_list">
        {% for non_field_error in form.non_field_errors %}
        <li>{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>
    <table id="controller">
        <tr>
            <td style="text-align:center;"><input type="submit" value="ログイン" class="square_btn" /></td>
        </tr>    
    </table>

</form>
</div>
{% endblock %}

templates/susanowo/shiryou_list.html
{% extends "susanowo/base.html" %}

{% load static %}
{% block body %}
<script src="{% static 'js/susanowo/shiryou.js' %}" ></script>
<form method="post" action="{% url 'susanowo:shiryou_delete' %}" id="shiryou_delete">
    {% csrf_token %}

    <div id="header" style="position: relative; left:100px;">
        参考資料
    </div>

    <div id="todo_list" style="position: relative; left:100px;">
        <div id="gtd_date">
            {{today}}
        </div>

        <!-- ========== テーブル全体を表す div ========== -->
        <div style="width:800px; border-style:solid;border-width:1px;">
        <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
            <div style="width:100%">
                <table class="list_class">
                    <thead>
                        <tr>
                            <th class="th_class" style='width:50px'>削除<input type="checkbox" id="chkAllDel" onchange="allCheckChange(); return false;"></th>
                            <th class="th_class" style='width:200px'>タイトル</th>
                            <th class="th_class" style='width:550px'>内容</th>
                            <th class="th_class" style='width:50px'>添付</th>
                        </tr>
                    </thead>
                </table>
            </div>
            <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
            <div style="height:400px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#BBBBBB">
                <table id="shiryou" class="list_class">
                    <tbody>
                        {% for todo in ttodos %}
                        <tr id="row{{todo.id}}" class="normal_row">
                            <td class="checkbox_class" style='width:50px'>
                                <input id="deleted_{{todo.id}}" name="deleted" class="checkbox_class" type="checkbox" value="{{todo.id}}" />
                            <td>
                            <td style='width:200px'>{{todo.title}}<td>
                            <td style='width:550px'>{{todo.discription}}<td>
                            <td style='width:50px'><a href="{% url 'susanowo:shiryou' todo.id %}" >資料</a><td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
            
    </div>

    <table id="controller" style="position: relative; left:100px;">
        <tr>
            <td style="width:100px;text-align:center;"><input type="submit" value="削除" class="square_btn" /></td>
            <td style="width:300px;text-align:center;"><a href="/susanowo/index" class="square_btn">キャンセル</a></td>
        </tr>    
    </table>
</form>
{% endblock %}