amenouzume/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "amenouzume"
urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^menu/$', views.menu, name='menu'),
    url(r'^place/$', views.place, name='place'),
    url(r'^place_input/$', views.place_input, name='place_input'),
    path('place_input_modify/<int:id>/<str:shori>', views.place_input_modify, name='place_input_modify'),
    url(r'^item/$', views.item, name='item'),
    url(r'^item_input/$', views.item_input, name='item_input'),
    path('item_input_modify/<int:id>/<str:shori>', views.item_input_modify, name='item_input_modify'),
    url(r'^place_item/$', views.place_item, name='place_item'),
    url(r'^place_item_list/$', views.place_item_list, name='place_item_list'),
    url(r'^stock_data/$', views.stock_data, name='stock_data'),
    url(r'^stock_data_history/$', views.stock_data_history, name='stock_data_history'),
    url(r'^get_users/$', views.get_users, name='get_users'),
    # url(r'^download_stock_data/$', views.download_stock_data, name='download_stock_data'),
    path('download_stock_data/<str:user_id>', views.download_stock_data, name='download_stock_data'),
    path('download_user_data', views.download_user_data, name='download_user_data'),
    path('download_place_data/<str:user_id>', views.download_place_data, name='download_place_data'),
    path('download_item_data/<str:user_id>', views.download_item_data, name='download_item_data'),
    # path('upload_stock_data/<str:stocks>', views.upload_stock_data, name='upload_stock_data'),
    url(r'^upload_stock_data/$', views.upload_stock_data, name='upload_stock_data'),
    url(r'^upload_stock_data_test/$', views.upload_stock_data_test, name='upload_stock_data_test'),
]

izanagi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('susanowo/', include('susanowo.urls')),
    path('guestboard/', include('guestboard.urls')), 
    # url(r'^guestboard/', include(('guestboard.urls', 'guestboard'),)), 
    # path('uploader/', include('uploader.urls')), 
    url(r'^uploader/', include('uploader.urls')), 
    path('omoikane/', include('omoikane.urls')),
    path('tukuyomi/', include('tukuyomi.urls')),
    path('amaterasu/', include('amaterasu.urls')),
    path('amenouzume/', include('amenouzume.urls')),
    path('sarutahiko/', include('sarutahiko.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amenouzume/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class MPlace(models.Model):
    
    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    place_name = models.CharField(
        verbose_name='場所名',
        max_length=100,
        blank=False,
    )

    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

class MItem(models.Model):
    
    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    item_name = models.CharField(
        verbose_name='品目名',
        max_length=100,
        blank=False,
    )

    safety_amt = models.DecimalField(
        verbose_name='安全在庫数',
        max_digits=5,
        decimal_places=2,
        blank=False,
        default=0.00,
    )

    item_term = models.IntegerField(
        verbose_name='在庫期間',
        blank=False,
    )

    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

class MItemPlace(models.Model):
    
    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    item_id = models.CharField(
        verbose_name='品目名',
        max_length=100,
        blank=False,
    )

    place_id = models.CharField(
        verbose_name='場所',
        max_length=100,
        blank=False,
    )

    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

class TStock(models.Model):
    
    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    item_id = models.IntegerField(
        verbose_name='品目ID',
        blank=False,
    )

    place_id = models.IntegerField(
        verbose_name='場所',
        blank=False,
    )

    item_name = models.CharField(
        verbose_name='品目名',
        max_length=100,
        blank=True,
    )

    safety_amt = models.IntegerField(
        verbose_name='安全在庫数',
        blank=False,
        default=0,
    )

    item_amt = models.IntegerField(
        verbose_name='在庫数',
        blank=True,
    )

    download_date = models.DateTimeField(
        verbose_name='ダウンロード日時',
        blank=True,
        default=now,
    )

    upload_date = models.DateTimeField(
        verbose_name='アップロード日時',
        blank=True,
        default=now,
    )

    buy_amt = models.IntegerField(
        verbose_name='購入数',
        blank=True,
    )

    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

class TStockHistory(models.Model):
    
    user_id = models.CharField(
        verbose_name='利用者コード',
        max_length=30,
        blank=False,
    )

    item_id = models.CharField(
        verbose_name='品目名',
        max_length=100,
        blank=False,
    )

    place_id = models.CharField(
        verbose_name='場所',
        max_length=100,
        blank=False,
    )

    item_name = models.CharField(
        verbose_name='品目名',
        max_length=100,
        blank=True,
    )

    safety_amt = models.IntegerField(
        verbose_name='安全在庫数',
        blank=False,
        default=0,
    )

    item_amt = models.IntegerField(
        verbose_name='在庫数',
        blank=True,
    )

    download_date = models.DateTimeField(
        verbose_name='ダウンロード日時',
        blank=True,
    )

    upload_date = models.DateTimeField(
        verbose_name='アップロード日時',
        max_length=100,
        blank=True,
    )

    buy_amt = models.IntegerField(
        verbose_name='購入数',
        blank=True,
    )

    create_date = models.DateTimeField(
        verbose_name='登録日時',
        blank=True,
        default=now,
    )

    create_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    create_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_date = models.DateTimeField(
        verbose_name='更新日時',
        blank=True,
        default=now,
    )

    update_pg_id = models.CharField(
        max_length=30,
        blank=True,
    )

    update_user_id = models.CharField(
        max_length=30,
        blank=True,
    )

amenouzume/forms.py
from django import forms
from django.forms import formsets
from django.forms import models
from omoikane.models import (
    MUser,
)
from amenouzume.models import (
    MPlace,
    MItem,
    MItemPlace,
    TStock,
)

class LoginModelForm(forms.ModelForm):
    
    class Meta:
        model = MUser
        fields = ('user_id','password')
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

class PlaceModelForm(forms.ModelForm):
    
    class Meta:
        model = MPlace
        fields = ('place_name',)
        widgets = {
            'place_name': forms.TextInput(),
        }

class PlaceDeleteModelForm(forms.ModelForm):
    
    class Meta:
        model = MPlace
        fields = ('place_name',)
        widgets = {
            'place_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

class ItemModelForm(forms.ModelForm):
    
    class Meta:
        model = MItem
        fields = ('item_name','safety_amt','item_term')

class ItemDeleteModelForm(forms.ModelForm):
    
    class Meta:
        model = MItem
        fields = ('item_name','safety_amt','item_term')
        widgets = {
            'item_name': forms.TextInput(attrs={'readonly': 'readonly'}),
            'safety_amt': forms.TextInput(attrs={'readonly': 'readonly'}),
            'item_term': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

class PlaceHeaderForm(forms.Form):
    
    place_name = forms.ChoiceField(
        required=False,
        label='場所名',
        widget=forms.Select(attrs={'place_id': 'place_name',})
    )

class ItemListForm(forms.ModelForm):
    
    is_select = forms.BooleanField(
        label='選択',
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'check'}
        ),
    )

    item_id = forms.CharField(label='品目ID',
        widget=forms.HiddenInput(),
    )

    place_name = forms.CharField(
        label='在庫名',
        required=False,
        widget=forms.HiddenInput(),
    )

    class Meta:
        model = MItem
        fields = ('id','item_name')
        widgets = {
            'id': forms.HiddenInput(),
            'item_name': forms.HiddenInput(),
            # 'item_name': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

ItemListFormSet = formsets.formset_factory(form=ItemListForm, extra=0,)

class StockItemForm(forms.ModelForm):

    item_name = forms.CharField(
        label='品目名',
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    safety_amt = forms.IntegerField(
        label='安全在庫数',
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    class Meta:
        model = MItemPlace
        fields = ('id','item_id','item_name','safety_amt')
        widgets = {
            'id': forms.HiddenInput(),
            'item_id': forms.HiddenInput(),
            # 'item_name': forms.TextInput(attrs={'readonly': 'readonly'}),
            # 'safety_amt': forms.TextInput(attrs={'readonly': 'readonly'}),
        }

StockItemFormSet = formsets.formset_factory(form=StockItemForm, extra=0,)

class StockDataForm(forms.Form):
    
    is_select = forms.BooleanField(
        label='選択',
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'check'}
        ),
    )

    place_id = forms.CharField(label='在庫場所ID',
        widget=forms.HiddenInput(),
    )

    place_name = forms.CharField(label='在庫場所名',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
    )

    item_data = StockItemFormSet()

StockDataFormSet = formsets.formset_factory(form=StockDataForm, extra=0,)

class StockDataFormTest(forms.ModelForm):
    
    class Meta:
        model = TStock
        fields = ('id','user_id','item_id','item_name','place_id','item_amt','safety_amt','buy_amt')
        widgets = {
            'id': forms.TextInput(),
            'user_id': forms.TextInput(),
            'item_id': forms.TextInput(),
            'item_name': forms.TextInput(),
            'place_id': forms.TextInput(),
            'item_amt': forms.TextInput(),
            'safety_amt': forms.TextInput(),
            'buy_amt': forms.TextInput(),
        }

class StockDataUploadForm(forms.Form):
    
    is_select = forms.BooleanField(
        label='選択',
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'check'}
        ),
    )

    item_data = StockItemFormSet()

tukuyomi/forms/loginForm.py
from django import forms
from django.forms import formsets
from django.forms import models
from omoikane.models import MUser

class LoginModelForm(forms.ModelForm):

    class Meta:
        model = MUser
        fields = ('user_id','password')
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }

    def clean(self):
        cleaned_data = super().clean()
        v_user_id = cleaned_data.get('user_id') 
        v_password = cleaned_data.get('password')
        user = None
        try:
            user = MUser.objects.get(user_id=v_user_id)
        except:
            raise forms.ValidationError("ユーザIDが存在しません。")

        if not user.password==v_password:
            raise forms.ValidationError("パスワードが違います。")

        return cleaned_data

tukuyomi/views/loginView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
import logging
import os
from izanagi import settings
from tukuyomi.forms.loginForm import LoginModelForm
from omoikane.models import MUser

def login(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        form = LoginModelForm(request.GET or None)
        context = {
            'form': form
        }

        if user_id:
            return redirect('/tukuyomi/menu/')

        return render(request, 'tukuyomi/login.html',context)

    elif request.method == 'POST':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')
        if user_id is None:
            user_id = request.POST['user_id']
            user = MUser.objects.get(user_id=user_id)
            user_name = user.user_name
            request.session['LOGIN_USER_ID'] = user.user_id
            request.session['LOGIN_USER_NAME'] = user.user_name

        form = LoginModelForm(request.POST)
        if form.is_valid():
            return redirect('/tukuyomi/menu/')
        else:
            context = {
                'user_id': user_id,
                'user_name': user_name,
                'form': form,
            }
            return render(request, 'tukuyomi/login.html', context)

tukuyomi/views/menuView.py
from django.shortcuts import (
    render, 
    redirect,
    get_object_or_404,
    reverse,
)
from django.http import HttpResponse
from django.utils import timezone
from django import forms
import datetime
from datetime import datetime
import logging
import os
from tukuyomi import tukuyomiConst
from tukuyomi.models.mbuyer import MBuyer

def menu(request):
    if request.method == 'GET':
        user_id = request.session.get('LOGIN_USER_ID')
        user_name = request.session.get('LOGIN_USER_NAME')

    # 定数初期化
    mbuyers = MBuyer.objects.filter(user_id=user_id).order_by('buyerNm')
    tukuyomiConst.BUYER_CHOICE = []
    tukuyomiConst.BUYER_CHOICE.append((None, ''))
    for buyer in mbuyers:
        tukuyomiConst.BUYER_CHOICE.append((buyer.id, buyer.buyerNm))

    context = {
        'user_id':user_id,
        'user_name':user_name,
        'now_year':datetime.strftime(datetime.now(), '%Y'),
        'now_month':datetime.strftime(datetime.now(), '%m'),
        # 'now_year':datetime.strftime(datetime.today(), '%Y'),
        # 'now_month':datetime.strftime(datetime.today(), '%m'),
        'form': None,
    }

    return render(request, 'tukuyomi/menu.html',context)

templates/amenouzume/base.html
{% load static %}
<!DOCTYPE himl>
<html>
    <head lang='ja'>
    <meta charset='UTF-8'>
    <title>
        在庫管理
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <LINK rel="shortcut icon" href="{% static 'icon/amenouzume.ico' %}">
    <link rel="stylesheet" href="{% static 'css/amenouzume/amenouzume.css' %}" >
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" >
    <script src="{% static 'js/jquery-3.3.1.js' %}" ></script>
    <script src="{% static 'js/jquery-ui.js' %}" ></script>
    <script src="{% static 'js/bootstrap.js' %}" ></script>
    <script src="{% static 'js/common.js' %}" ></script>
    {% block header %}
    {% endblock %}
</head>
<body>
    {{message}}
    <table style="width:100%;height:100%;">
        <tbody>
            <tr>
                <th style="width:250px;height:25px;text-align:center;" class="menu" colspan="2">
                    <img src="{% static 'png/amenouzume/amenouzume_title.png' %}"/><br/>
                    <a class="menu_class" style="color:#39437a; background-color: #ffffff;" href="{% url 'amenouzume:menu' %}" >
                    <h4>
                        在庫管理システム
                    </h4>
                    </a>
                </th>
                <td style="text-align:right; width:auto;height:20px" class="menu">
                    {{user_id}}({{user_name}})<br/><br/>
                    <a class="menu_class" style="color:#39437a;" href="/amenouzume/">ログアウト</a>
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:100px;height:1px" class="menu">
                </td>
                <td style="text-align:right; width:100px;height:1px" class="menu">
                </td>
                <td style="text-align:right; height:1px" class="menu">
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:200px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'amenouzume:place' %}" >
                        場所マスタ登録
                    </a>
                </td>
                <td class="main_body" colspan="2" rowspan="6">
                    {% block body %}
                    {% endblock %}
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:200px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'amenouzume:item' %}" >
                        品目マスタ登録
                    </a>
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:200px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'amenouzume:place_item' %}" >
                        在庫品目マスタ登録
                    </a>
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:200px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'amenouzume:stock_data' %}" >
                        在庫データ作成
                    </a>
                </td>
            </tr>
            <tr>
                <td style="text-align:right; width:200px;height:25px" class="menu th_center_class">
                    <a class="menu_class" href="{% url 'amenouzume:stock_data_history' %}" >
                        在庫データ履歴参照
                    </a>
                </td>
            </tr>
            <tr>
                <td class="menu th_center_class"></td>
            </tr>
        </tbody>
    </table>
    <br/>
    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>

</body>
</html>

templates/amenouzume/item.html
{% extends "amenouzume/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/amenouzume/menu.js' %}" ></script>
{% endblock %}

{% block body %}
<form method="post" enctype="multipart/form-data" action="{% url 'amenouzume:item_input' %}">
    {% csrf_token %}
    <div class="title_class">
        品目一覧<br/><br/>
    </div>
    <table style="text-align: center;">
        <tr class="tr_class">
            <th style="width: 500px;" class="th_center_class th_header">品目名</th>
            <th style="width: 200px;" class="th_center_class th_header">安全在庫</th>
            <th style="width: 200px;" class="th_center_class th_header">在庫期間</th>
            <th class="th_center_class th_header">更新</th>
            <th class="th_center_class th_header">削除</th>
        </tr>
        {% for form in forms %}
        <tr class="tr_class">
            <td class="td_left_class">{{form.item_name}}</td>
            <td class="td_right_class">{{form.safety_amt}}</td>
            <td class="td_right_class">{{form.item_term}}</td>
            <td class="td_center_class"><a href="{% url 'amenouzume:item_input_modify' form.id　'm' %}"><img src="{% static 'png/common/edit.png' %}"></a></td>
            <td class="td_center_class"><a href="{% url 'amenouzume:item_input_modify' form.id 'd' %}"><img src="{% static 'png/common/delete.png' %}"></a></td>
        </tr>
    {% endfor %}
    </table>
    <table id="controller">
        <tr>
            <td style="text-align:center;"><input type="submit" value="新規" class="square_btn" /></td>
        </tr>    
    </table>
</form>
{% endblock %}

templates/amenouzume/item_input.html
{% extends "amenouzume/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/amenouzume/place_input.js' %}" ></script>
{% endblock %}

{% block body %}
{% ifequal shori '' %}
    <form method="post" action="{% url 'amenouzume:item_input' %}">
{% else %}
    <form method="post" action="{% url 'amenouzume:item_input_modify' id shori %}">
{% endifequal %}

    {% csrf_token %}
    {% ifequal shori '' %}
    <div class="title_class">
        品目登録<br/><br/>
    </div>
        
    <table class="simple_class">
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_name.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_name}}{{form.item_name.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.safety_amt.label}}</th>
            <td style="width:500px" class="td_class">{{form.safety_amt}}{{form.safety_amt.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_term.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_term}}{{form.item_term.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% ifequal shori 'm' %}
    品目登録
    <table class="simple_class">
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_name.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_name}}{{form.item_name.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.safety_amt.label}}</th>
            <td style="width:500px" class="td_class">{{form.safety_amt}}{{form.safety_amt.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_term.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_term}}{{form.item_term.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% ifequal shori 'd' %}
    品目削除
    <table class="simple_class">
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_name.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_name}}{{form.item_name.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.safety_amt.label}}</th>
            <td style="width:500px" class="td_class">{{form.safety_amt}}{{form.safety_amt.errors.0}}</td>
        </tr>
        <tr>
            <th style="width:100px" class="th_right_class th_header">{{form.item_term.label}}</th>
            <td style="width:500px" class="td_class">{{form.item_term}}{{form.item_term.errors.0}}</td>
        </tr>
    </table>
    {% endifequal %}

    {% if form.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in form.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>
    <table id="controller">
        <tr>
            {% ifequal shori 'd' %}
                <td style="text-align:center;"><input type="submit" value="削除" class="square_btn" /></td>
            {% else %}
                <td style="text-align:center;"><input type="submit" value="登録" class="square_btn" /></td>
            {% endifequal %}
            <td style="text-align:center;"><input type="button" id="btn_cancel" value="キャンセル" class="square_btn" /></td>
        </tr>    
    </table>

{% endblock %}

templates/amenouzume/place_item.html
{% extends "amenouzume/base.html" %}

{% load static %}
{% block header %}
<script src="{% static 'js/amenouzume/place_item.js' %}" ></script>
{% endblock %}

{% block body %}
<div class="title_class">
    在庫品目マスタ登録<br/><br/>
</div>
在庫品目マスタ登録<br/><br/>

<form method="post" action="{% url 'amenouzume:place_item' %}">
    {% csrf_token %}
    在庫場所：{{place.place_name}}
    <input type="submit" value="検索" id="btnPlaceList" class="square_btn" />
</form>

<form method="post" action="{% url 'amenouzume:place_item_list' %}">
    {% csrf_token %}
    <input type="hidden" id="id_place_id" name="place_id" value="{{cmb_place_id}}" />
    <!-- ========== テーブル全体を表す div ========== -->
    <div style="width:650px; border-style:solid;border-width:0px;">
    <!-- ===== ヘッダ部(THEAD相当)を表す div ===== -->
        <div style="width:100%">
            <table class="list_class">
                <thead>
                    <tr>
                        <th class="th_class" style='width:50px'>選択</th>
                        <th class="th_class" style='width:300px'>品目名</th>
                        <th class="th_class" style='width:300px'>場所名</th>
                    </tr>
                </thead>
            </table>
        </div>
        <!-- ===== ボディー部(TBODY相当)を表す div ===== -->
        <div style="height:250px; width:100%;overflow-y:scroll;overflow-x:hidden;background:#FFFFFF">
            {{ formSet.management_form }}
            <table class="list_class">
                <tbody name="placeitem">
                {% for placeitem in formSet %}
                    <tr id="row">
                        <td class="td_class" style='width:50px'>
                            {{placeitem.is_select}}
                        <td>
                        <td class="td_class" style='width:300px'>
                            {{placeitem.item_name.value}}
                        </td>
                        <td class="td_class" style='width:300px'>
                            {{placeitem.place_name.value}}
                        </td>
                        <td>
                            {{placeitem.item_id}}
                            {{placeitem.item_name}}
                            {{placeitem.place_name}}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% if formSet.non_field_errors %}
    <br/>
    <div class="errmsg">
        <ul>
        {% for non_field_error in formSet.non_field_errors %}
        <li class="errmsg">{{ non_field_error }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <br/>
    <table id="controller">
        <tr>
            <td style="text-align:center;"><input type="submit" value="登録" class="square_btn" /></td>
            <td style="text-align:center;"><input type="button" id="btn_cancel" value="キャンセル" class="square_btn" /></td>
        </tr>    
    </table>

{% endblock %}